# Generated by Django 3.2.1 on 2024-01-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECCInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('order_of_curve', 'Order of Curve'), ('order_of_point', 'Order of Point'), ('find_y', 'Find Y'), ('generator_point', 'Generator Point')], max_length=20)),
                ('a', models.PositiveIntegerField()),
                ('b', models.PositiveIntegerField()),
                ('p', models.PositiveIntegerField()),
                ('x', models.PositiveBigIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('curve_type', models.PositiveSmallIntegerField(choices=[(1, 'Short Weierstrass'), (2, 'Twisted Edwards'), (3, 'Montgomery')], max_length=20)),
            ],
        ),
    ]
